### ISSUE TITLE
can't find vcpkg.json using hikogui as submodule

### ISSUE THREAD

**Issue by Anesthesia4** [hikoworks/hikogui#665]
when I use hikogui as a submodule, CMake can't find vcpkg.json, I checked CMakeList.txt and found that lines 40,47,68 use ${CMAKE_SOURCE_DIR}, should it be ${CMAKE_CURRENT_SOURCE_DIR}?

**Comment by takev** [comment]
Thank you, I will see if I can fix this quickly.
